### PR TITLE
Hotfix/add new event callback

### LINKED ISSUE #107: Interpipesink sends SIGSEGV upstream and causes segmentation fault on GST 1.19.2
Only on latest version of GStreamer 1.19.2:

Interpipesink sends SIGSEGV on src pad of first element before it and cause the segmentation fault.

For example:

`audiotestsrc ! audioconvert ! queue ! interpipesink sync=false async=false`

back trace in gdb:

```
Thread 2 "queue0:src" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff495b700 (LWP 98051)]
0x0000555555acf7c0 in ?? ()
(gdb) bt
#0  0x0000555555acf7c0 in  ()
#1  0x00007ffff4967eaf in gst_app_sink_event (sink=0x555555ad3780 [GstBaseSink|outputSinkEnsoniq_AudioPCI], event=0x555555ad1920) at ../subprojects/gst-plugins-base/gst-libs/gst/app/gstappsink.c:901
#2  0x00007ffff64e4b29 in gst_inter_pipe_sink_event (base=0x555555ad3780 [GstBaseSink|outputSinkEnsoniq_AudioPCI], event=0x555555ad1920) at ../gst/interpipe/gstinterpipesink.c:586
#3  0x00007ffff6d21522 in gst_base_sink_event (pad=<optimized out>, parent=0x555555ad3780 [GstObject|outputSinkEnsoniq_AudioPCI], event=0x555555ad1920) at ../subprojects/gstreamer/libs/gst/base/gstbasesink.c:3677
#4  0x00007ffff7ea5ae7 in gst_pad_send_event_unchecked (pad=pad@entry=0x555555ac4c30 [GstPad|sink], event=event@entry=0x555555ad1920, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at ../subprojects/gstreamer/gst/gstpad.c:5900
#5  0x00007ffff7ea6024 in gst_pad_push_event_unchecked (pad=pad@entry=0x555555ac49e0 [GstPad|src], event=0x555555ad1920, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at ../subprojects/gstreamer/gst/gstpad.c:5544
#6  0x00007ffff7ea6494 in push_sticky (pad=pad@entry=0x555555ac49e0 [GstPad|src], ev=ev@entry=0x7ffff495ab30, user_data=user_data@entry=0x7ffff495aba0) at ../subprojects/gstreamer/gst/gstevent.h:425
#7  0x00007ffff7ea3ee8 in events_foreach (pad=pad@entry=0x555555ac49e0 [GstPad|src], func=func@entry=0x7ffff7ea6440 <push_sticky>, user_data=user_data@entry=0x7ffff495aba0) at ../subprojects/gstreamer/gst/gstpad.c:608
#8  0x00007ffff7eb0b81 in check_sticky (event=0x555555ad1920, pad=0x555555ac49e0 [GstPad|src]) at ../subprojects/gstreamer/gst/gstpad.c:4106
#9  0x00007ffff7eb0b81 in gst_pad_push_event (pad=0x555555ac49e0 [GstPad|src], event=event@entry=0x555555ad1920) at ../subprojects/gstreamer/gst/gstpad.c:5675
#10 0x00007ffff49b6093 in gst_queue_push_one (queue=0x555555aca080 [GstQueue|queue0]) at ../subprojects/gstreamer/plugins/elements/gstqueue.c:1459
#11 0x00007ffff49b6093 in gst_queue_loop (pad=<optimized out>) at ../subprojects/gstreamer/plugins/elements/gstqueue.c:1541
#12 0x00007ffff7edf211 in gst_task_func (task=0x555555ad9050 [GstTask|queue0:src]) at ../subprojects/gstreamer/gst/gsttask.c:384
#13 0x00007ffff7d24bb3 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff7d24215 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff7793164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#16 0x00007ffff7516def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

No matter the source (video or audio) or pads capabilities same happens.

### PR DESCRIPTION
**Pull request by jafet-chaves**
resolves #107

### CODE REVIEW

File: gst/interpipe/gstinterpipesink.c [hunk 1]
```diff
@@ -213,6 +217,9 @@ gst_inter_pipe_sink_init (GstInterPipeSink * sink)
   callbacks.eos = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_eos);
   callbacks.new_sample = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_buffer);
   callbacks.new_preroll = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_preroll);
+#if GST_VERSION_MINOR >= 19
+  callbacks.new_event = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_event);
```
Comment (michaelgruner) [inline gst/interpipe/gstinterpipesink.c:221]: We don't actually want to implement this callback. Let's set it to null so the base class knows it doesn't need to call anything. The reason it is attempting to invoke the callback is because the struct was likely initialized randomly and the pointer is non-null (making the base class think it contains a valid method). I recommend initializing the callback struct to zero, or memsetting it out. This way this won't happen again if GStreamer adds another callback.

**Review by michaelgruner — CHANGES_REQUESTED** [review]

File: gst/interpipe/gstinterpipesink.c [hunk 2]
```diff
@@ -209,10 +209,15 @@ gst_inter_pipe_sink_init (GstInterPipeSink * sink)
 
   g_mutex_init (&sink->listeners_mutex);
 
+  memset (&callbacks, 0, sizeof (callbacks));
```
Comment (lleon95) [inline gst/interpipe/gstinterpipesink.c:212]: I think you can initialise it in the declaration:

```c
GstAppSinkCallbacks callbacks = {0};
```

File: gst/interpipe/gstinterpipesink.c [hunk 3]
```diff
@@ -209,10 +209,15 @@ gst_inter_pipe_sink_init (GstInterPipeSink * sink)
...
+
   /* AppSink callbacks */
   callbacks.eos = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_eos);
   callbacks.new_sample = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_buffer);
   callbacks.new_preroll = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_preroll);
+#if GST_VERSION_MINOR >= 19
+  callbacks.new_event = NULL;
+#endif
```
Comment (lleon95) [inline gst/interpipe/gstinterpipesink.c:220]: Since you are setting the whole `callbacks` struct, you don't need to set it to `NULL` given that it is already NULL

**Review by lleon95 — CHANGES_REQUESTED** [review]

**Comment by lleon95** [comment]
I think we can take advantage of it and fix the copyright year in the README:

```
GstInterpipe copyright (C) 2016 RidgeRun LLC
```

File: gst/interpipe/gstinterpipesink.c (hunk 2 above)
Comment (jafet-chaves) [reply gst/interpipe/gstinterpipesink.c:212]: I think this just comes down to a matter of taste. I prefer the current implementation due to the alignment bytes also being set to zero in the case of memset.

File: gst/interpipe/gstinterpipesink.c (hunk 3 above)
Comment (jafet-chaves) [reply gst/interpipe/gstinterpipesink.c:220]: You are right, this is redundant

**Review by lleon95 — APPROVED** [review]

**Review by mleivaf — APPROVED** [review]

**Review by michaelgruner — APPROVED** [review]
